export default [
  {
    id: 1,
    int: 1,
    fraccion: '1111.11.11',
    descripcion: 'este es el reporte número uno',
    nombre: 'reporte número uno',
    ligamento: 'tipo de ligamento',
    lig: 'segundo ligamento',
    acabado: 'tipo de acabado',
    aca: 'segundo acabado',
    composicion: 'tipo de composición',
    filfib: 'filamento o fibra',
    gramaje: '100',
    ancho: '100',
    tejido: 'tipo de tejido',
    otros: 'otro tipo de datos',
    conclusion: 'conclusión',
    created_at: '2019-10-27T21:38:58.014Z',
    updated_at: '2019-10-27T22:52:25.274Z',
  },
  {
    id: 2,
    int: 2,
    fraccion: '2222.22.22',
    descripcion: 'este es el reporte número dos',
    nombre: 'reporte número dos',
    ligamento: 'tipo de ligamento',
    lig: 'segundo ligamento',
    acabado: 'tipo de acabado',
    aca: 'segundo acabado',
    composicion: 'tipo de composición',
    filfib: 'filamento o fibra',
    gramaje: '100',
    ancho: '100',
    tejido: 'tipo de tejido',
    otros: 'otro tipo de datos',
    conclusion: 'conclusión',
    created_at: '2019-11-27T21:38:58.014Z',
    updated_at: '2019-11-27T22:52:25.274Z',
  },
  {
    id: 3,
    int: 3,
    fraccion: '3333.33.33',
    descripcion: 'este es el reporte número tres',
    nombre: 'reporte número tres',
    ligamento: 'tipo de ligamento',
    lig: 'segundo ligamento',
    acabado: 'tipo de acabado',
    aca: 'segundo acabado',
    composicion: 'tipo de composición',
    filfib: 'filamento o fibra',
    gramaje: '100',
    ancho: '100',
    tejido: 'tipo de tejido',
    otros: 'otro tipo de datos',
    conclusion: 'conclusión',
    created_at: '2019-12-27T21:38:58.014Z',
    updated_at: '2019-12-27T22:52:25.274Z',
  },
  {
    id: 4,
    int: 4,
    fraccion: '4444.44.44',
    descripcion: 'este es el reporte número cuatro',
    nombre: 'reporte número cuatro',
    ligamento: 'tipo de ligamento',
    lig: 'segundo ligamento',
    acabado: 'tipo de acabado',
    aca: 'segundo acabado',
    composicion: 'tipo de composición',
    filfib: 'filamento o fibra',
    gramaje: '100',
    ancho: '100',
    tejido: 'tipo de tejido',
    otros: 'otro tipo de datos',
    conclusion: 'conclusión',
    created_at: '2020-10-27T21:38:58.014Z',
    updated_at: '2020-10-27T22:52:25.274Z',
  },
  {
    id: 5,
    int: 5,
    fraccion: '5555.55.55',
    descripcion: 'este es el reporte número cinco',
    nombre: 'reporte número cinco',
    ligamento: 'tipo de ligamento',
    lig: 'segundo ligamento',
    acabado: 'tipo de acabado',
    aca: 'segundo acabado',
    composicion: 'tipo de composición',
    filfib: 'filamento o fibra',
    gramaje: '100',
    ancho: '100',
    tejido: 'tipo de tejido',
    otros: 'otro tipo de datos',
    conclusion: 'conclusión',
    created_at: '2020-11-27T21:38:58.014Z',
    updated_at: '2020-11-27T22:52:25.274Z',
  },
]
